<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carrier Title_ko_unique_7</name>
   <tag></tag>
   <elementGuidId>5f33aa68-dd79-4e2d-87b3-89e3f408b0b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ko_unique_7&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ko_unique_7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef63b310-74af-4177-8418-5c832a632dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6c08ce53-d5b2-4e8e-97dd-6a266a05599e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>370a4401-d7ec-4932-9a82-dec249cef4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {'aria-labelledby': 'label_method_' + method.method_code + '_' + method.carrier_code + ' ' + 'label_carrier_' + method.method_code + '_' + method.carrier_code,
                    'checked': element.rates().length == 1 || element.isSelected}, value: method.carrier_code + '_' + method.method_code, checked: element.isSelected</value>
      <webElementGuid>f10572d0-7b9f-4df5-b903-8f0e27de0159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_method_flatrate_flatrate label_carrier_flatrate_flatrate</value>
      <webElementGuid>e017d5f8-29c0-4899-9ab4-ca23d5a9a04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>flatrate_flatrate</value>
      <webElementGuid>8600efa4-73a3-4db4-a16a-f6a5d87d4c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ko_unique_7</value>
      <webElementGuid>8d67a8b1-cdc7-4b25-8b48-659a61094e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-shipping-method-load&quot;)/table[@class=&quot;table-checkout-shipping-method&quot;]/tbody[1]/tr[@class=&quot;row&quot;]/td[@class=&quot;col col-method&quot;]/input[@class=&quot;radio&quot;]</value>
      <webElementGuid>8fde953f-4f43-47b3-bd41-abd69ad18cc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ko_unique_7']</value>
      <webElementGuid>c5121344-747c-4733-a133-8d7a78623604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-shipping-method-load']/table/tbody/tr/td/input</value>
      <webElementGuid>3d441d14-2d38-4dc9-a677-4c539673d1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>7bc96530-bf62-42e1-8854-0fd4e205140a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ko_unique_7']</value>
      <webElementGuid>50bc2a93-3ccf-4e74-90ef-3acee8cf09f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
