<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Welcome, Riska Putri</name>
   <tag></tag>
   <elementGuidId>610092f9-9304-4f5b-97c5-a54b40947a7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.logged-in</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/header/div[1]/div/ul/li[1]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Welcome, Riska Putri!' or . = 'Welcome, Riska Putri!')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>14841935-b141-4691-8c9c-ced95368b8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logged-in</value>
      <webElementGuid>2a97d0f6-54fd-426c-943b-a1fa13df42e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: new String('Welcome, %1!').replace('%1', customer().fullname)</value>
      <webElementGuid>bd1acf4a-e427-4793-9320-5e124b9e803d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome, Riska Putri!</value>
      <webElementGuid>9f5ca36e-f050-463c-ac84-5cdf7c157cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;account customer-account-index page-layout-2columns-left&quot;]/div[@class=&quot;page-wrapper&quot;]/header[@class=&quot;page-header&quot;]/div[@class=&quot;panel wrapper&quot;]/div[@class=&quot;panel header&quot;]/ul[@class=&quot;header links&quot;]/li[@class=&quot;greet welcome&quot;]/span[@class=&quot;logged-in&quot;]</value>
      <webElementGuid>2436c897-8052-48bc-b51a-b4eb5728545a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>/html/body/div[1]/header/div[1]/div/ul/li[1]/span</value>
      <webElementGuid>0a34388b-7371-4a3a-8260-7a9298e2e81d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
